# Generated by Django 2.2.4 on 2019-08-28 09:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_profileuser_is_qualified'),
        ('objects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='admin_seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='object',
            name='approved_object',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='object',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.ProfileUser')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='objects.Object')),
            ],
        ),
    ]
