# Generated by Django 2.2.4 on 2019-10-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0003_auto_20190927_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.TextField(default=5),
            preserve_default=False,
        ),
    ]
