# Generated by Django 2.2.4 on 2019-10-08 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0005_auto_20191002_1246'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='type',
            field=models.CharField(default='Restaurant', max_length=100),
        ),
    ]
