# Generated by Django 2.2.4 on 2019-11-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0006_auto_20191008_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='type',
        ),
        migrations.AddField(
            model_name='object',
            name='email',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='object',
            name='phone',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='object',
            name='site',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
