# Generated by Django 2.2.4 on 2019-11-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0007_auto_20191112_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='facebook',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='object',
            name='instagram',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='object',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='object',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='object',
            name='site',
            field=models.CharField(default='', max_length=100),
        ),
    ]
