# Generated by Django 2.2.4 on 2019-11-13 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0009_auto_20191113_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='rating',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='object',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.City'),
        ),
    ]
