# Generated by Django 2.2.4 on 2019-11-13 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('objects', '0010_auto_20191113_1219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beautysalon',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='carservice',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='carwash',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='fastfood',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='fun',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='object',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='other',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='restaurant',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='sportfitness',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AddField(
            model_name='object',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_objects.object_set+', to='contenttypes.ContentType'),
        ),
    ]
