# Generated by Django 2.2.4 on 2019-11-13 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0011_auto_20191113_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='category_bg_name',
            field=models.CharField(default='Ресторант', max_length=100),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='category_en_name',
            field=models.CharField(default='restaurants', max_length=100),
        ),
    ]
