# Generated by Django 2.2.4 on 2019-11-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0012_auto_20191113_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='beautysalon',
            name='bg_name',
            field=models.CharField(default='Салон за красота', max_length=100),
        ),
        migrations.AddField(
            model_name='beautysalon',
            name='category_bg_name',
            field=models.CharField(default='Салони за красота', max_length=100),
        ),
        migrations.AddField(
            model_name='beautysalon',
            name='category_en_name',
            field=models.CharField(default='beautysalon', max_length=100),
        ),
        migrations.AddField(
            model_name='carservice',
            name='bg_name',
            field=models.CharField(default='Автосервиз', max_length=100),
        ),
        migrations.AddField(
            model_name='carservice',
            name='category_bg_name',
            field=models.CharField(default='Автосервизи', max_length=100),
        ),
        migrations.AddField(
            model_name='carservice',
            name='category_en_name',
            field=models.CharField(default='carservice', max_length=100),
        ),
        migrations.AddField(
            model_name='fastfood',
            name='bg_name',
            field=models.CharField(default='Бързо хранене', max_length=100),
        ),
        migrations.AddField(
            model_name='fastfood',
            name='category_bg_name',
            field=models.CharField(default='Бързо хранене', max_length=100),
        ),
        migrations.AddField(
            model_name='fastfood',
            name='category_en_name',
            field=models.CharField(default='fastfood', max_length=100),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='bg_name',
            field=models.CharField(default='Ресторант', max_length=100),
        ),
        migrations.AddField(
            model_name='sportfitness',
            name='bg_name',
            field=models.CharField(default='Спорт и фитнес', max_length=100),
        ),
        migrations.AddField(
            model_name='sportfitness',
            name='category_bg_name',
            field=models.CharField(default='Спорт и фитнес', max_length=100),
        ),
        migrations.AddField(
            model_name='sportfitness',
            name='category_en_name',
            field=models.CharField(default='sportfitness', max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='category_bg_name',
            field=models.CharField(default='Ресторанти', max_length=100),
        ),
    ]
