# Generated by Django 2.2.4 on 2019-11-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0015_auto_20191120_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='admin_seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='approved_object',
            field=models.BooleanField(default=False),
        ),
    ]
