# Generated by Django 2.2.4 on 2019-11-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0016_auto_20191120_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='carwash',
            name='bg_name',
            field=models.CharField(default='Автомивка', max_length=100),
        ),
        migrations.AddField(
            model_name='carwash',
            name='category_bg_name',
            field=models.CharField(default='Автомивка', max_length=100),
        ),
        migrations.AddField(
            model_name='carwash',
            name='category_en_name',
            field=models.CharField(default='carwash', max_length=100),
        ),
        migrations.AddField(
            model_name='fun',
            name='bg_name',
            field=models.CharField(default='Забавление', max_length=100),
        ),
        migrations.AddField(
            model_name='fun',
            name='category_bg_name',
            field=models.CharField(default='Забавление', max_length=100),
        ),
        migrations.AddField(
            model_name='fun',
            name='category_en_name',
            field=models.CharField(default='fun', max_length=100),
        ),
        migrations.AddField(
            model_name='other',
            name='bg_name',
            field=models.CharField(default='Други', max_length=100),
        ),
        migrations.AddField(
            model_name='other',
            name='category_bg_name',
            field=models.CharField(default='Други', max_length=100),
        ),
        migrations.AddField(
            model_name='other',
            name='category_en_name',
            field=models.CharField(default='other', max_length=100),
        ),
    ]
