# Generated by Django 2.2.4 on 2019-08-22 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profileuser_is_qualified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileuser',
            name='is_qualified',
        ),
    ]
